# Generated by Django 4.1.3 on 2022-12-10 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('photo', models.URLField()),
                ('genre', models.CharField(choices=[('Romance', 'romance'), ('Mystery', 'mystery'), ('Fantasy and Science Fiction', 'fantasy-and-sci-fi'), ('Thrillers and Horrors', 'thrillers-and-horrors'), ('Young Adult', 'young-adult'), ('Self-help', 'self-help'), ('Biography, Autobiography and Memoir', 'biography-autobiography-and-memoir'), ('Esoteric', 'esoteric')], max_length=35)),
                ('biography', models.TextField(choices=[('Romance', 'romance'), ('Mystery', 'mystery'), ('Fantasy and Science Fiction', 'fantasy-and-sci-fi'), ('Thrillers and Horrors', 'thrillers-and-horrors'), ('Young Adult', 'young-adult'), ('Self-help', 'self-help'), ('Biography, Autobiography and Memoir', 'biography-autobiography-and-memoir'), ('Esoteric', 'esoteric')])),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('publication_date_and_time', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publication_date_and_time',),
            },
        ),
    ]
