# Generated by Django 4.1.3 on 2022-12-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_alter_author_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='biography',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='author',
            name='genre',
            field=models.CharField(blank=True, choices=[('Romance', 'Romance'), ('Mystery', 'Mystery'), ('Fantasy and Science Fiction', 'Fantasy and Science Fiction'), ('Thrillers and Horrors', 'Thrillers and Horrors'), ('Young Adult', 'Young Adult'), ('Self-help', 'Self-help'), ('Biography, Autobiography and Memoir', 'Biography, Autobiography and Memoir'), ('Esoteric', 'Esoteric')], max_length=35),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.URLField(blank=True),
        ),
    ]
