# Generated by Django 4.1.3 on 2022-12-15 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('author', '0004_alter_author_biography_alter_author_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
