# Generated by Django 4.1.3 on 2022-12-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Romance', 'romance'), ('Mystery', 'mystery'), ('Fantasy and Science Fiction', 'fantasy-and-sci-fi'), ('Thrillers and Horrors', 'thrillers-and-horrors'), ('Young Adult', 'young-adult'), ('Self-help', 'self-help'), ('Biography, Autobiography and Memoir', 'biography-autobiography-and-memoir'), ('Esoteric', 'esoteric')], max_length=35),
        ),
    ]
