# Generated by Django 4.1.3 on 2022-12-09 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='pet',
            new_name='book',
        ),
    ]
