# Generated by Django 4.1.3 on 2022-12-10 11:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_bookreview_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='publication_date_and_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
