# Generated by Django 4.1.3 on 2022-12-10 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_bookreview_publication_date_and_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-publication_date_and_time',)},
        ),
        migrations.AlterModelOptions(
            name='bookreview',
            options={'ordering': ('-publication_date_and_time',)},
        ),
        migrations.AddField(
            model_name='book',
            name='publication_date_and_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
