# Generated by Django 4.1.3 on 2022-12-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_photo',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('Romance', 'Romance'), ('Mystery', 'Mystery'), ('Fantasy and Science Fiction', 'Fantasy and Science Fiction'), ('Thrillers and Horrors', 'Thrillers and Horrors'), ('Young Adult', 'Young Adult'), ('Self-help', 'Self-help'), ('Biography, Autobiography and Memoir', 'Biography, Autobiography and Memoir'), ('Esoteric', 'Esoteric')], max_length=35),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
