# Generated by Django 4.1.3 on 2022-12-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_alter_book_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='number_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
