# Generated by Django 4.1.3 on 2022-11-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='username',
            field=models.CharField(default='', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
