# Generated by Django 4.1.3 on 2022-12-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_bio_alter_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.URLField(default='https://s26162.pcdn.co/wp-content/uploads/2018/01/rawImage-861x1024.jpg'),
            preserve_default=False,
        ),
    ]
