# Generated by Django 4.1.3 on 2022-12-16 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_news_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-publication_date_and_time',), 'verbose_name_plural': 'news'},
        ),
    ]
