# Generated by Django 4.1.3 on 2022-12-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
    ]
